//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.07 at 03:26:21 PM BRT 
//


package gov.goias.bindings;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the infoconv package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: infoconv
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ConsultarCPFP3 }
     * 
     */
    public ConsultarCPFP3 createConsultarCPFP3() {
        return new ConsultarCPFP3();
    }

    /**
     * Create an instance of {@link ConsultarCPFP3Response }
     * 
     */
    public ConsultarCPFP3Response createConsultarCPFP3Response() {
        return new ConsultarCPFP3Response();
    }

    /**
     * Create an instance of {@link ArrayOfPessoaPerfil3 }
     * 
     */
    public ArrayOfPessoaPerfil3 createArrayOfPessoaPerfil3() {
        return new ArrayOfPessoaPerfil3();
    }

    /**
     * Create an instance of {@link ConsultarCPFP3T }
     * 
     */
    public ConsultarCPFP3T createConsultarCPFP3T() {
        return new ConsultarCPFP3T();
    }

    /**
     * Create an instance of {@link ConsultarCPFP3TResponse }
     * 
     */
    public ConsultarCPFP3TResponse createConsultarCPFP3TResponse() {
        return new ConsultarCPFP3TResponse();
    }


    public PessoaPerfil3 createPessoaPerfil3() {
        return new PessoaPerfil3();
    }



}
